[package]
name = "constants"
version.workspace = true
edition.workspace = true
authors.workspace = true
app_name.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
